package com.findit.app.ui.theme

import androidx.compose.ui.graphics.Color

// Palette sampled from the app icon:
// background cream #F8F3D5, box #D0954F/#B77248, tail taupe #7D6D5C, item red #D94F42.
val Primary = Color(0xFF8B4D20)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFF5D3A4)
val OnPrimaryContainer = Color(0xFF2F1400)

val Secondary = Color(0xFF7D6D5C)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE8DED0)
val OnSecondaryContainer = Color(0xFF2A2118)

val Tertiary = Color(0xFFD94F42)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFFFD8D1)
val OnTertiaryContainer = Color(0xFF410002)

val Background = Color(0xFFFFFBEB)
val OnBackground = Color(0xFF211A13)
val Surface = Color(0xFFFFFBEB)
val OnSurface = Color(0xFF211A13)
val SurfaceDim = Color(0xFFE7D8BF)
val SurfaceBright = Color(0xFFFFFBEB)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFFFF7E3)
val SurfaceContainer = Color(0xFFF8F0DC)
val SurfaceContainerHigh = Color(0xFFF2E6CF)
val SurfaceContainerHighest = Color(0xFFEBDDC4)
val SurfaceVariant = Color(0xFFF1E5D1)
val OnSurfaceVariant = Color(0xFF5D5144)
val Outline = Color(0xFF8B7C6B)
val OutlineVariant = Color(0xFFD8C7AD)
val Error = Color(0xFFBA3A2F)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFD8D1)
val OnErrorContainer = Color(0xFF410002)

// Dark theme colors
val PrimaryDark = Color(0xFFF1BC7B)
val OnPrimaryDark = Color(0xFF4D2600)
val PrimaryContainerDark = Color(0xFF6D3809)
val OnPrimaryContainerDark = Color(0xFFF5D3A4)

val SecondaryDark = Color(0xFFCDBFAA)
val OnSecondaryDark = Color(0xFF3F2D18)
val SecondaryContainerDark = Color(0xFF55483A)
val OnSecondaryContainerDark = Color(0xFFE8DED0)

val TertiaryDark = Color(0xFFFFB4AA)
val OnTertiaryDark = Color(0xFF690005)
val TertiaryContainerDark = Color(0xFF8D2F28)
val OnTertiaryContainerDark = Color(0xFFFFD8D1)

val BackgroundDark = Color(0xFF1F1B16)
val OnBackgroundDark = Color(0xFFEDE0D0)
val SurfaceDark = Color(0xFF1F1B16)
val OnSurfaceDark = Color(0xFFEDE0D0)
val SurfaceDimDark = Color(0xFF1F1B16)
val SurfaceBrightDark = Color(0xFF3A3128)
val SurfaceContainerLowestDark = Color(0xFF17130F)
val SurfaceContainerLowDark = Color(0xFF272119)
val SurfaceContainerDark = Color(0xFF2C251D)
val SurfaceContainerHighDark = Color(0xFF372E24)
val SurfaceContainerHighestDark = Color(0xFF43382C)
val SurfaceVariantDark = Color(0xFF4C4034)
val OnSurfaceVariantDark = Color(0xFFD8C7AD)
val OutlineDark = Color(0xFFA49380)
val OutlineVariantDark = Color(0xFF4C4034)
val ErrorDark = Color(0xFFFFB4AA)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF8D2F28)
val OnErrorContainerDark = Color(0xFFFFD8D1)
